# Dockerfile-nodejs

FROM node:10.14.2-alpine
MAINTAINER kanagawa App Developer Ltd

RUN npm uninstall -g create-react-app
RUN npm install -g create-react-app
RUN npm install axios react-router react-bootstrap bootstrap react-router-dom node-sass@4.12.0 redux@4.0.4
